[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
max_global_rejects = 10000000000
# See more config options https://github.com/gakonst/foundry/tree/master/config